# Set root logger level to DEBUG and its only appender to A1. 

log4j.rootLogger= ALL, A1

# Set test loggers demoLogger and develoLogger

log4j.logger.demoLogger=ERROR
log4j.logger.develLogger=DEBUG

# A1 is set to be a ConsoleAppender.

log4j.appender.A1=org.apache.log4j.ConsoleAppender

# A1 uses TTCCLayout.

log4j.appender.A1.layout=org.apache.log4j.TTCCLayout