
= PAX-LOGGING

The goal of this project is to allow users and bundles to use well known Logging APIs like SLF4J or Commons-Logging.

There should be a distinction between _Logging API_ which, by itself, doesn't do any log, but instead requires specific logging implementation (and related configuration) and the _Logging implementation_ itself.

Logging APIs (or _Facades_) matching the above distinction include:

* https://www.slf4j.org/[SLF4J]
* https://commons.apache.org/proper/commons-logging/[Commons Logging]
* https://osgi.org/specification/osgi.cmpn/7.0.0/service.log.html[OSGi Compendium Log Service]
* http://docs.jboss.org/hibernate/orm/4.3/topical/html/logging/Logging.html[JBoss Logging]

Logging implementations always provide their own _APIs_ and can be used without any of the above facades. These include:

* https://logging.apache.org/log4j/1.2/[Apache Log4j]
* https://logging.apache.org/log4j/2.x/[Apache Log4j2]
* https://logback.qos.ch/[Logback]

== Different Logging APIs

The fundamental interface is `org.osgi.service.log.LogService` from Chapter 101 of OSGi Compendium specification.
The history of `org.osgi.service.log` package versions is:

* `1.0`: OSGi R1
* `1.1`: OSGi R2
* `1.2`: OSGi R3
* `1.3`: OSGi R4, R4.1, R4.2, R4.3, R5, R6
* `1.4`: OSGi R7

pax-logging-api uses version `1.3` from OSGi Compendium R6.

=== SLF4J

`slf4j-api-1.7.26-sources.jar` contains more sources than `slf4j-api-1.7.26.jar` has classes - in particular, `org.slf4j.impl` package is removed from the jar and the responsibility to provide:

* `org.ops4j.impl.StaticLoggerBinder`
* `org.ops4j.impl.StaticMDCBinder`
* `org.ops4j.impl.StaticMarkerBinder`

classes lies on the side of _binding library_ for SLF4J API. Such classes are provided by (among others):

* `logback-classic-1.2.3.jar`
* `log4j-slf4j-impl-2.11.2.jar`
* `slf4j-nop-1.7.26.jar`
* `slf4j-log4j12-1.7.26.jar`
* `slf4j-simple-1.7.26.jar`

pax-logging-api provides own implementation of these three classes. All other classes are directly repackaged (using bndlib) from `slf4j-api-1.7.26.jar` - classes that don't have to be changed are no longer shipped in pax-logging-api source directory.

=== Commons Logging
=== Log4j
=== Log4j2
=== Apache JULI
=== JBoss Logging
=== Knopflerfish

https://www.knopflerfish.org/archive.html[This page] shows Knopflerfish releases groupped by OSGi release version.

Knopflerfish 6 matches OSGi R6 and `org.osgi.service.log` version `1.3`.